#!/bin/ksh
#
# Submit sms job script to loadleveler.
#
# Usage:
# 	llsubmit4 %SMSJOB% %SMSNAME% %SMSTRIES% %SMSTRYNO% 
# 
# NOTE:
#	Variable WORKDIR must be set in the shell environment.
#
# Version:
# 	v1.0 2015.04.27

usage() {
  echo "Submit sms job script to loadleveler."
  echo "Usage: llsubmit4 %SMSJOB% %SMSNAME% %SMSTRIES% %SMSTRYNO%"
}

err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@"
}

submit_log() {
	if [[ "$SUBMIT_LOG" = "true" ]]; then
		echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]$@" >> ${submit_log}
	fi
}

debug() {
	if [[ "$DEBUG" = "true" ]]; then
		echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]$@" >> ${debug_log}
	fi
}

error_log() {
	if [[ "$ERROR_LOG" = "true" ]]; then
		echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]$@" >> ${error_log}
	fi
}

# for test use
export DEBUG=false
export SUBMIT_LOG=true
export ERROR_LOG=true

export log_dir=$WORKDIR/sublog
# for nwp_qu only
if [[ $USER = nwp_qu ]] ; then
    export log_dir=/cma/g1/nwp_qu/sublog
fi 

export submit_log=${log_dir}/llsubmit4.submit.log
export debug_log=${log_dir}/llsubmit4.debug.log
export error_log=${log_dir}/llsubmit4.error.log

test -d ${log_dir} ||mkdir -p ${log_dir}

if [[ $# -ne 4 ]] 
then
  err "error params"
  usage
  exit 1
fi

set -u
set -ex

jobname=
taskname=
smstries=
smstryno=
jobout=

jobname=$1
taskname=$2
smstries=$3
smstryno=$4

if [[ ! -n "${jobout}" ]]
then
	jobout=$( echo ${jobname} | sed 's/job\([0-9]*\)$/\1/g' )
fi
job_err_output_file=${jobout}.err

debug "${jobname} ${taskname} ${smstries} ${smstryno}"

# name of sms server.
if [[ $USER = nwp ]] ; then
  nameofsms=nwpc_op
elif [[ $USER = nwp_qu ]] ; then
  nameofsms=nwpc_qu
elif [[ $USER = nwp_sp ]] ; then
  nameofsms=nwpc_sp
elif [[ $USER = nwp_ex ]] ; then
  nameofsms=nwpc_ex
elif [[ $USER = nwp_xp ]] ; then
  nameofsms=nwpc_xp
elif [[ $USER = nwp_pd ]] ; then
    nameofsms=nwpc_pd
else
  nameofsms=nwpc_$USER
fi

# wait for a random time between SMSTRYNO and 5 seconds.
/usr/bin/python -c 'import random,time;random_seconds=random.uniform('${smstryno}',5);time.sleep(random_seconds);'

if [[ ! -n "${jobout}" ]]
then
	jobout=$( echo ${jobname} | sed 's/job\([0-9]*\)$/\1/g' )
fi
job_err_output_file=${jobout}.err



# test if job file exisits.
if [ ! -f $jobname ]; then
    sleep 5
    if [ ! -f $jobname ]; then
        cat > ${job_err_output_file} <<EOF
[$(date +"%Y-%m-%d %H:%M:%S")] Job file does not exist.
EOF
        cdp <<EOF
login $nameofsms $USER 1
force -r aborted $taskname
exit
EOF
        exit
    fi
fi

submit_log "llsubmit $jobname"
name=$(llsubmit $jobname 2>>${submit_log})
#name=$( llsubmit asdfasdfasdf 2>>${submit_log})

rid=$(echo $name | cut -d '"' -f 2)

if [ -n "$rid" ]; then
	debug "llsubmit success $taskname"
	cdp <<EOF
login $nameofsms $USER 1
alter -v $taskname SMSRID $rid
exit
EOF

else
	debug "submit failed $taskname at TRYNO $smstryno"
	if [[ $smstryno -ge $smstries ]]; then
		debug "abort $taskname after $smstries tries"
		cat > ${job_err_output_file} <<EOF
[$(date +"%Y-%m-%d %H:%M:%S")] Failed to submit job to loadleveler after $smstries tries.
EOF
		error_log "[llsubmit4]submit failed: $@"
		cdp <<EOF
login $nameofsms $USER 1
force -r aborted $taskname
exit
EOF
	else
		debug "rerun $taskname after TRYNO $smstryno"
		cat > ${job_err_output_file} <<EOF
[$(date +"%Y-%m-%d %H:%M:%S")] Failed to submit job to loadleveler at tryno $smstryno.
EOF
		error_log "[llsubmit4]submit failed: $@"
		cdp <<EOF
login $nameofsms $USER 1
run -f $taskname
exit
EOF
	fi

fi
